import pandas as pd
from pathlib import Path

DATASET = Path("koi_training_data.csv")
RANKED = Path("artifacts_physics_grouped/earthlike_candidates.csv")
OUTPUT_DIR = Path("artifacts_physics_grouped")

df = pd.read_csv(DATASET)
ranked = pd.read_csv(RANKED)

# Candidate names generated by the ranking pipeline
names = ranked["kepoi_name"].tolist()

# Columns needed for validation
cols = [
    "kepoi_name",
    "kepid",
    "koi_disposition",
    "koi_pdisposition",
    "koi_score",
    "koi_period",
    "koi_prad",
    "koi_insol",
    "koi_teq",
    "koi_steff",
    "koi_srad",
    "koi_smass",
    "f_rho_ratio",
    "f_log_rho_ratio",
    "f_duration_ratio",
    "f_duration_unphysical",
    "f_impact_implied",
    "f_impact_discrepancy",
    "f_depth_ratio",
]

validation = df[df["kepoi_name"].isin(names)][cols].copy()

# Preserve the ranking generated by the model
validation = ranked[
    [
        "final_rank",
        "kepoi_name",
        "planet_probability",
        "earthlike_score",
    ]
].merge(
    validation,
    on="kepoi_name",
    how="left",
)

validation = validation.sort_values("final_rank")

# Add simple validation categories
validation["catalog_status"] = validation["koi_disposition"].map(
    {
        "CONFIRMED": "CONFIRMED",
        "CANDIDATE": "CANDIDATE",
        "FALSE POSITIVE": "FALSE_POSITIVE",
    }
).fillna("OTHER")

validation["density_consistent"] = (
    validation["f_rho_ratio"].between(0.7, 1.3)
)

validation["duration_consistent"] = (
    validation["f_duration_ratio"].between(0.5, 1.5)
    & ~validation["f_duration_unphysical"]
)

validation["depth_consistent"] = (
    validation["f_depth_ratio"].between(0.7, 1.3)
)

validation["overall_physics_consistent"] = (
    validation["density_consistent"]
    & validation["duration_consistent"]
    & validation["depth_consistent"]
)

# Save complete validation table
output_file = OUTPUT_DIR / "candidate_validation.csv"
validation.to_csv(output_file, index=False)

print("=" * 78)
print("EXOVISION AI — CANDIDATE VALIDATION")
print("=" * 78)

print(f"Ranked candidates: {len(validation)}")
print()

print("CATALOG DISPOSITION")
print("-" * 78)
print(validation["catalog_status"].value_counts().to_string())
print()

print("PHYSICS CONSISTENCY")
print("-" * 78)
print(
    "Density consistent:",
    validation["density_consistent"].sum(),
    "/",
    len(validation),
)
print(
    "Duration consistent:",
    validation["duration_consistent"].sum(),
    "/",
    len(validation),
)
print(
    "Depth consistent:",
    validation["depth_consistent"].sum(),
    "/",
    len(validation),
)
print(
    "Overall physics consistent:",
    validation["overall_physics_consistent"].sum(),
    "/",
    len(validation),
)
print()

print("RANKED VALIDATION TABLE")
print("-" * 78)

display_cols = [
    "final_rank",
    "kepoi_name",
    "planet_probability",
    "earthlike_score",
    "catalog_status",
    "koi_prad",
    "koi_insol",
    "koi_teq",
    "f_rho_ratio",
    "f_duration_ratio",
    "f_depth_ratio",
    "overall_physics_consistent",
]

print(
    validation[display_cols]
    .to_string(index=False)
)

print()
print("Saved:")
print(output_file)
print("=" * 78)